### PR TITLE
feat(prtoc): copy imported pb files

### PR DESCRIPTION
**Pull request by artemchernyak-outreach**
## What this PR does / why we need it

This was the only path to make this change non breaking. This approach simply make the process of copying `.pb` files automatic.

This approach places the files in the same location as repos currently expect them to be. I tried many different approaches to getting things to import from other locations and none seemed to work. The common consensus on the node grpc plugin issues list is to follow the same process as well. 

## Jira ID

[DT-2822]

## Notes for your reviewers

[DT-2822]: https://outreach-io.atlassian.net/browse/DT-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by george-e-shaw-iv — COMMENTED** [review]
are we going to .gitignore these or have service owners commit them?

**Comment by george-e-shaw-iv** [comment]
this also begs the question - should we just be doing this for ruby and go too? we're duplicating data now and resolving .proto dependencies differently between ruby/go and node now

**Comment by artemchernyak-outreach** [comment]
@george-e-shaw-iv Yes, I was planning to open a separate PR to update the `.gitignore` file to ignore that folder.

As far as this diverging from the ruby an Go process, that's just us dealing with the realities of the generation tooling. We have not receive any reports of issues with Go or Ruby, and based on some testing, both seem to handle imports correctly without needing the files to exist in the same folder.

This seems to be an isolated issue to the node grpc plugin and therefore it require special handling. You can see more details here https://github.com/agreatfool/grpc_tools_node_protoc_ts/issues/67.

**Comment by artemchernyak-outreach** [comment]
One correction (shouldn't answer so late at night). We do expect people to check these in. That's the current process and this should not change it in any way. As a test for this, I tested it with https://github.com/getoutreach/commitbridge/tree/main/api/clients/node/src/grpc. They import `orgapi` and if you run `make gogenerate` without these changes, it remove all the `orgapi` files from that directory. With these changes, there is no diff.

**Review by pbr0ck3r — APPROVED** [review]

**Review by jaredallard — APPROVED** [review]

**Pull request merged**
