### PR TITLE
feat: Added Telefork API key for CLI telemetry

### PR DESCRIPTION
**Pull request by plisy**
… today

## What this PR does / why we need it

We are going to use Telefork for getting CLI telemetry. For that we need the API key we now store in vault. The API key is public, included in our other clients already.

## Jira ID

[DTSS-1629]

## Notes for your reviewers

[DTSS-1629]: https://outreach-io.atlassian.net/browse/DTSS-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ChrisPRobinson — APPROVED** [review]
LGTM

**Comment by george-e-shaw-iv** [comment]
How are people who can't sign into our vault (anyone who isn't an outreach engineer) going to get the token?

**Comment by plisy** [comment]
> How are people who can't sign into our vault (anyone who isn't an outreach engineer) going to get the token?

How do they get the honeycomb key now?

**Comment by george-e-shaw-iv** [comment]
And we're taking a prerequisite on running devconfig before building CLIs now? Is that already a thing? I assume the idea is to compile them in actually - so my first comment doesn't matter as much but still kind of matters

**Comment by plisy** [comment]
> And we're taking a prerequisite on running devconfig before building CLIs now? Is that already a thing? I assume the idea is to compile them in actually - so my first comment doesn't matter as much but still kind of matters

It's exactly the same thing we do with honeycomb now.

**Pull request merged**
